env: # Environment variables to pass to all tasks
    CIRRUS_CLONE_DEPTH: 1 # No need to clone with the whole history
    CIRRUS_WORKING_DIR: "/tmp/ci" # Where to clone the aosp-builder repo

# store our secrets here
    github_token: "ENCRYPTED[!630b836f70acf32da17712abf49e6cedc395fbf7adfa3023b34bd64a516640e03f3e133b4feefb1f723e36472592a6b8!]"
    bot_api: "ENCRYPTED[!78df93af52b276deba904023576dbf45df5be7a833cb3a83509bcc6af9981f3a8882bf67dadc2ab4a786279a38f2e390!]"
    chat_id: "ENCRYPTED[!a264d4e3e40adec008386e2db5ad751254dd8abf8120ffeb6e79733aae14ccc4f64f4b02d9be49116be00cad64474dc4!]"

# store information about git here
    gmail: doodle280204@gmail.com

task:
    name: aosp
    timeout_in: 260m
    container:
      image: aarunalr/aosp-build
      cpu: 8
      memory: 32G
    download_ccache_background_script: # To download ccache in background
      - curl -o /tmp/ci/function https://raw.githubusercontent.com/projects-nexus/cirrus-script/main/function
      - curl -o /tmp/ci/download_ccache https://raw.githubusercontent.com/projects-nexus/cirrus-script/main/download_ccache
      - bash download_ccache # Ccache download script
    sync_script:
      - bash sync
    build_script:
      - curl -o build https://raw.githubusercontent.com/projects-nexus/cirrus-script/main/build
      - bash build
    upload_ccache_script: # Upload ccache to cloud foreground
      - curl -o upload_ccache https://raw.githubusercontent.com/projects-nexus/cirrus-script/main/upload_ccache
      - bash upload_ccache # Ccache uploading script
