#!/bin/bash

mkdir -p /tmp/rom # Where to sync source
cd /tmp/rom
. /tmp/ci/function

SECONDS=0

# Sync source
repo init --depth=1 --no-repo-verify -u https://github.com/PixelOS-Pixelish/manifest -b twelve -g default,-mips,-darwin,-notdefault

# Sync source without unnecessary messages, try with -j30 first, if fails, it will try again
repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all) || repo sync -c --no-clone-bundle --no-tags --optimized-fetch --prune --force-sync -j$(nproc --all)

# local manifest
git clone --depth=1 https://github.com/$CIRRUS_REPO_OWNER/device_xiaomi_whyred -b master device/xiaomi/whyred
git clone --depth=1 https://github.com/$CIRRUS_REPO_OWNER/vendor_xiaomi_whyred -b master vendor/xiaomi/whyred
git clone --depth=1 https://github.com/$CIRRUS_REPO_OWNER/android_kernel_xiaomi_whyred -b master kernel/xiaomi/whyred

tg "Cloned all Sources Successfully!
Time Took: $(($SECONDS / 60)) minute(s) and $(($SECONDS % 60)) second(s).
Status: $progress"

echo "$(($SECONDS / 60))" > /tmp/sync_time.txt
